import 'dart:convert';
import 'package:flutter/material.dart';
import '../../../core/errors/app_error.dart';
import '../models/manual_sync_action.dart';
import '../services/manual_sync_action_service.dart';

class ManualSyncActionsScreen extends StatefulWidget { const ManualSyncActionsScreen({super.key}); @override State<ManualSyncActionsScreen> createState()=>_State(); }
class _State extends State<ManualSyncActionsScreen> {
  final service=ManualSyncActionService(), search=TextEditingController();
  List<ManualSyncAction> items=const []; bool loading=true; String status='ATTENTION_REQUIRED';
  static const statuses=['ATTENTION_REQUIRED','PENDING','CORRECTION_REQUIRED','FAILED','PROCESSING','COMPLETED','REJECTED','ALL'];
  @override void initState(){super.initState();load();} @override void dispose(){search.dispose();super.dispose();}
  String pretty(dynamic value){if(value==null)return '—';try{final decoded=value is String?jsonDecode(value):value;return const JsonEncoder.withIndent('  ').convert(decoded);}catch(_){return value.toString();}}
  Future<void> load() async {setState(()=>loading=true);try{final rows=await service.list(status:status,search:search.text);if(mounted)setState(()=>items=rows);}catch(e){message('Load failed: $e');}finally{if(mounted)setState(()=>loading=false);}}
  void message(String text)=>ScaffoldMessenger.of(context).showSnackBar(SnackBar(content:Text(friendlyErrorMessage(text))));
  Color color(String s)=>s=='COMPLETED'?Colors.green:s=='FAILED'?Colors.red:s=='CORRECTION_REQUIRED'?Colors.orange:s=='PROCESSING'?Colors.blue:Colors.blueGrey;
  Future<String?> notesDialog(String title) async {final c=TextEditingController();return showDialog<String>(context:context,builder:(x)=>AlertDialog(title:Text(title),content:TextField(controller:c,decoration:const InputDecoration(labelText:'Administrator notes',border:OutlineInputBorder()),maxLines:3),actions:[TextButton(onPressed:()=>Navigator.pop(x),child:const Text('Cancel')),FilledButton(onPressed:()=>Navigator.pop(x,c.text),child:const Text('Confirm'))]));}
  Future<void> open(ManualSyncAction item) async {var current=await service.get(item.id);if(!mounted)return;await showDialog<void>(context:context,builder:(outer)=>StatefulBuilder(builder:(ctx,setLocal){
    Future<void> correct() async {final c=TextEditingController(text:pretty(current.payload));final accepted=await showDialog<bool>(context:ctx,builder:(d)=>AlertDialog(title:const Text('Correct working payload'),content:SizedBox(width:760,height:450,child:TextField(controller:c,expands:true,maxLines:null,minLines:null,decoration:const InputDecoration(border:OutlineInputBorder(),helperText:'Identity fields are immutable. Enter valid JSON.'))),actions:[TextButton(onPressed:()=>Navigator.pop(d,false),child:const Text('Cancel')),FilledButton(onPressed:()=>Navigator.pop(d,true),child:const Text('Save'))]));if(accepted==true){try{current=await service.correct(current.id,jsonDecode(c.text),'Corrected in ERP');setLocal((){});}catch(e){message('Correction failed: $e');}}}
    Future<void> execute() async {final ok=await showDialog<bool>(context:ctx,builder:(d)=>AlertDialog(title:const Text('Execute payload?'),content:Text('This will POST to ${current.endpoint} using the protected idempotency key. The full attempt and response will be audited.'),actions:[TextButton(onPressed:()=>Navigator.pop(d,false),child:const Text('Cancel')),FilledButton(onPressed:()=>Navigator.pop(d,true),child:const Text('Execute'))]));if(ok==true){try{current=await service.process(current.id);setLocal((){});}catch(e){message('Execution failed: $e');}}}
    return AlertDialog(title:Text('Manual sync ${current.id}'),content:SizedBox(width:900,height:650,child:ListView(children:[Wrap(spacing:18,runSpacing:10,children:[fact('Status',current.status),fact('Entity',current.entityType),fact('Device',current.deviceId),fact('Local record',current.localRecordId),fact('Request','${current.method} ${current.endpoint}'),fact('Attempts','${current.attemptCount}'),fact('HTTP response','${current.responseStatus ?? '—'}'),fact('Idempotency key',current.idempotencyKey??'—')]),if((current.failureResponse??'').isNotEmpty)...section('Original device failure',current.failureResponse!),if((current.lastError??'').isNotEmpty)...section('Latest execution error',current.lastError!),...section('Original payload (read-only)',pretty(current.originalPayload)),...section('Working payload',pretty(current.payload)),...section('Backend response',pretty(current.responseBody)),if(current.attempts.isNotEmpty)...section('Attempt audit history',pretty(current.attempts))])),actions:[TextButton(onPressed:()=>Navigator.pop(outer),child:const Text('Close')),OutlinedButton.icon(onPressed:current.status=='PROCESSING'||current.status=='COMPLETED'?null:correct,icon:const Icon(Icons.edit),label:const Text('Correct payload')),OutlinedButton.icon(onPressed:current.status=='PROCESSING'||current.status=='COMPLETED'?null:()async{final n=await notesDialog('Reject manual action');if(n!=null){current=await service.reject(current.id,n);setLocal((){});}},icon:const Icon(Icons.block),label:const Text('Reject')),FilledButton.icon(onPressed:['PENDING','FAILED','CORRECTION_REQUIRED'].contains(current.status)?execute:null,icon:const Icon(Icons.play_arrow),label:const Text('Execute payload'))]);}));await load();}
  Widget fact(String l,String v)=>SizedBox(width:250,child:Column(crossAxisAlignment:CrossAxisAlignment.start,children:[Text(l,style:const TextStyle(fontWeight:FontWeight.bold)),SelectableText(v)]));
  List<Widget> section(String title,String body)=>[const SizedBox(height:16),Text(title,style:Theme.of(context).textTheme.titleMedium),const SizedBox(height:5),Container(padding:const EdgeInsets.all(12),decoration:BoxDecoration(color:Theme.of(context).colorScheme.surfaceContainerHighest,borderRadius:BorderRadius.circular(8)),child:SelectableText(body,style:const TextStyle(fontFamily:'monospace')))];
  @override Widget build(BuildContext context)=>Scaffold(appBar:AppBar(title:const Text('MawaPay Manual Sync Corrections'),actions:[IconButton(onPressed:load,icon:const Icon(Icons.refresh))]),body:Padding(padding:const EdgeInsets.all(16),child:Column(children:[Row(children:[Expanded(child:TextField(controller:search,onSubmitted:(_)=>load(),decoration:const InputDecoration(prefixIcon:Icon(Icons.search),labelText:'Search action, device, entity, endpoint or error',border:OutlineInputBorder()))),const SizedBox(width:12),DropdownButton<String>(value:status,items:statuses.map((s)=>DropdownMenuItem(value:s,child:Text(s.replaceAll('_',' ')))).toList(),onChanged:(v){if(v!=null){setState(()=>status=v);load();}}),const SizedBox(width:12),FilledButton(onPressed:load,child:const Text('Apply'))]),const SizedBox(height:12),Expanded(child:loading?const Center(child:CircularProgressIndicator()):items.isEmpty?const Center(child:Text('No manual sync actions match the filters.')):ListView.separated(itemCount:items.length,separatorBuilder:(_,__)=>const SizedBox(height:8),itemBuilder:(c,i){final x=items[i],tone=color(x.status);return Card(child:ListTile(leading:Icon(Icons.build_circle,color:tone),title:Text('${x.method} ${x.endpoint}'),subtitle:Text('${x.entityType} • device ${x.deviceId} • local ${x.localRecordId}\n${x.lastError??x.failureResponse??'Awaiting administrator action'}',maxLines:3,overflow:TextOverflow.ellipsis),trailing:Text(x.status.replaceAll('_',' '),style:TextStyle(color:tone,fontWeight:FontWeight.bold)),isThreeLine:true,onTap:()=>open(x)));}))]))));
}
