name: mawa_erp
description: "mawa"
publish_to: 'none'

version: 1.0.11+12

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  shared_preferences: ^2.3.5
  http: ^1.3.0
  intl: ^0.20.2
  file_picker: ^8.1.7
  image_picker: ^1.1.2
  url_launcher: ^6.3.1
  path_provider: ^2.1.5
  open_filex: ^4.5.0
  pdf: ^3.11.1
  printing: ^5.13.0
  package_info_plus: ^8.2.1
  blue_thermal_printer: ^1.2.3
  esc_pos_utils_plus: ^2.0.3
  go_router: ^14.8.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/branding/mawa_logo.png
    - assets/branding/mawa_logo_white.png
    - assets/branding/mawa_logo_red.png
    - assets/branding/mawa_app_icon.png
