import 'dart:typed_data';
import 'package:blue_thermal_printer/blue_thermal_printer.dart';
import 'package:esc_pos_utils_plus/esc_pos_utils_plus.dart';
import '../../features/membership/models/receipt_response.dart';
import 'setting_service.dart';

class BluetoothPrintService {
  static final BluetoothPrintService _instance = BluetoothPrintService._internal();
  factory BluetoothPrintService() => _instance;
  BluetoothPrintService._internal();

  final BlueThermalPrinter bluetooth = BlueThermalPrinter.instance;

  Future<List<BluetoothDevice>> getDevices() async {
    return await bluetooth.getBondedDevices();
  }

  Future<void> printMembershipReceipt(ReceiptResponse receipt, String memberName, {BluetoothDevice? device}) async {
    bool? isConnected = await bluetooth.isConnected;
    if (isConnected != true) {
      if (device == null) {
        throw Exception('No printer connected. Please select a printer.');
      }
      await bluetooth.connect(device);
    }

    // Load Company Info from Settings
    final settings = await SettingService().getSettings();
    final companyName = _getSetting(settings, 'NAME', 'mawa');
    final companyAddress = _getSetting(settings, 'ADDRESS-LINE-1', '');
    final companyPhone = _getSetting(settings, 'PHONE', '');

    final profile = await CapabilityProfile.load();
    final generator = Generator(PaperSize.mm58, profile);
    List<int> bytes = [];

    // Header - Center Aligned
    bytes += generator.text(companyName, 
        styles: const PosStyles(align: PosAlign.center, bold: true, height: PosTextSize.size2, width: PosTextSize.size2));
    if (companyAddress.isNotEmpty) {
      bytes += generator.text(companyAddress, styles: const PosStyles(align: PosAlign.center));
    }
    if (companyPhone.isNotEmpty) {
      bytes += generator.text('Tel: $companyPhone', styles: const PosStyles(align: PosAlign.center));
    }
    bytes += generator.hr();

    // Receipt Metadata
    bytes += generator.text('OFFICIAL RECEIPT', styles: const PosStyles(align: PosAlign.center, bold: true));
    bytes += generator.text('No: ${receipt.receiptNo}', styles: const PosStyles(align: PosAlign.center));
    bytes += generator.text('Date: ${receipt.receiptDate}', styles: const PosStyles(align: PosAlign.center));
    bytes += generator.hr();

    // Member & Payment Info
    bytes += generator.text('MEMBER: $memberName', styles: const PosStyles(bold: true));
    bytes += generator.text('MEMBERSHIP NO: ${receipt.membershipId}');
    bytes += generator.text('METHOD: ${receipt.paymentMethod}');
    bytes += generator.text('BATCH: ${receipt.paymentBatchNo}');
    bytes += generator.hr();

    // Table Header
    bytes += generator.row([
      PosColumn(text: 'PERIOD', width: 7, styles: const PosStyles(bold: true)),
      PosColumn(text: 'AMOUNT', width: 5, styles: const PosStyles(align: PosAlign.right, bold: true)),
    ]);
    bytes += generator.hr(ch: '-');

    // Table Rows (Allocations)
    for (var allocation in receipt.allocations) {
      bytes += generator.row([
        PosColumn(text: _formatPeriod(allocation.periodYYYYMM), width: 7),
        PosColumn(text: allocation.amount.toStringAsFixed(2), width: 5, styles: const PosStyles(align: PosAlign.right)),
      ]);
    }
    bytes += generator.hr();

    // Grand Total
    bytes += generator.row([
      PosColumn(text: 'TOTAL PAID', width: 7, styles: const PosStyles(bold: true, height: PosTextSize.size1)),
      PosColumn(text: 'R ${receipt.totalAmount.toStringAsFixed(2)}', width: 5, styles: const PosStyles(align: PosAlign.right, bold: true)),
    ]);
    bytes += generator.hr();

    // Footer
    bytes += generator.feed(1);
    bytes += generator.text('Thank you for your payment!', styles: const PosStyles(align: PosAlign.center));
    bytes += generator.text('Status: ${receipt.status}', styles: const PosStyles(align: PosAlign.center));
    bytes += generator.feed(1);
    bytes += generator.text('Generated by mawa', styles: const PosStyles(align: PosAlign.center, height: PosTextSize.size1));
    
    bytes += generator.feed(3);
    bytes += generator.cut();

    await bluetooth.writeBytes(Uint8List.fromList(bytes));
  }

  String _getSetting(List<dynamic> settings, String attribute, String defaultValue) {
    try {
      return settings.firstWhere((s) => s.attribute == attribute).value;
    } catch (_) {
      return defaultValue;
    }
  }

  String _formatPeriod(String period) {
    if (period.length != 6) return period;
    final year = period.substring(0, 4);
    final month = period.substring(4, 6);
    return '$month/$year';
  }
}
