import 'app_routes.dart';
import 'feature_group_registry.dart';

class WorkcenterRouteRegistry {
  static const Map<String, String> _mappings = {
    'MEMBERSHIP_MANAGEMENT': '/feature-groups/membership-management',
    'MEMBERSHIP-MANAGEMENT': '/feature-groups/membership-management',
    'FUNERAL_MANAGEMENT_GROUP': '/feature-groups/funeral-management',
    'FINANCE_MANAGEMENT': '/feature-groups/finance-management',
    'FINANCE-MANAGEMENT': '/feature-groups/finance-management',
    'PARTNER_MANAGEMENT': '/feature-groups/partner-management',
    'PARTNER-MANAGEMENT': '/feature-groups/partner-management',
    'ADMINISTRATION': '/feature-groups/administration',
    'SCHEDULING': AppRoutes.appointments,
    'MEMBERSHIP': AppRoutes.memberships,
    'MEMBER': AppRoutes.memberships,
    'MEMBERSHIPS': AppRoutes.memberships,
    'MEMBERSHIP_PLAN': AppRoutes.membershipPlans,
    'MEMBERSHIP-PLAN': AppRoutes.membershipPlans,
    'MEMBERSHIP_PLANS': AppRoutes.membershipPlans,
    'MEMBERSHIP-PLANS': AppRoutes.membershipPlans,
    'PLAN': AppRoutes.membershipPlans,
    'PLANS': AppRoutes.membershipPlans,
    'MEMBERSHIP_CLAIM': AppRoutes.membershipClaims,
    'MEMBERSHIP-CLAIM': AppRoutes.membershipClaims,
    'MEMBERSHIP_CLAIMS': AppRoutes.membershipClaims,
    'MEMBERSHIP-CLAIMS': AppRoutes.membershipClaims,
    'CLAIM': AppRoutes.membershipClaims,
    'CLAIMS': AppRoutes.membershipClaims,
    'GROUP_SOCIETY': AppRoutes.groupSocieties,
    'GROUP-SOCIETY': AppRoutes.groupSocieties,
    'GROUP_SOCIETIES': AppRoutes.groupSocieties,
    'GROUP-SOCIETIES': AppRoutes.groupSocieties,
    'SOCIETY': AppRoutes.groupSocieties,
    'SOCIETIES': AppRoutes.groupSocieties,
    'INVOICE': AppRoutes.invoices,
    'INVOICES': AppRoutes.invoices,
    'SYSTEM_CONFIGURATION': AppRoutes.settings,
    'SYSTEM-CONFIGURATION': AppRoutes.settings,
    'SYSTEM_CONFIG': AppRoutes.settings,
    'SYSTEM-CONFIG': AppRoutes.settings,
    'API_LOG': AppRoutes.apiLogs,
    'API-LOG': AppRoutes.apiLogs,
    'API_LOGS': AppRoutes.apiLogs,
    'API-LOGS': AppRoutes.apiLogs,
    'API_ENDPOINT_LOG': AppRoutes.apiLogs,
    'API-ENDPOINT-LOG': AppRoutes.apiLogs,
    'API_ENDPOINT_LOGS': AppRoutes.apiLogs,
    'API-ENDPOINT-LOGS': AppRoutes.apiLogs,
    'PAYMENT_REQUEST': AppRoutes.paymentRequests,
    'PAYMENT-REQUEST': AppRoutes.paymentRequests,
    'PAYMENT_REQUESTS': AppRoutes.paymentRequests,
    'PAYMENT-REQUESTS': AppRoutes.paymentRequests,
    'CASHUP': AppRoutes.cashups,
    'CASHUPS': AppRoutes.cashups,
    'CASH_UP': AppRoutes.cashups,
    'CASH-UP': AppRoutes.cashups,
    'CASES': AppRoutes.cases,
    'CASE': AppRoutes.cases,
    'CASE_MANAGEMENT': AppRoutes.cases,
    'LEGAL_CASE': AppRoutes.cases,
    'LEGAL-CASE': AppRoutes.cases,
    'LEGAL_CASES': AppRoutes.cases,
    'LEGAL_CASE_MANAGEMENT': AppRoutes.cases,
    'APPROVALS': AppRoutes.approvals,
    'APPROVAL': AppRoutes.approvals,
    'SETTINGS': AppRoutes.settings,
    'SYSTEM_SETTINGS': AppRoutes.settings,
    'PRODUCT': AppRoutes.products,
    'PRODUCTS': AppRoutes.products,
    'PRODUCT_MAINTENANCE': AppRoutes.products,
    'FNB_INTEGRATION_ADMIN': AppRoutes.fnbIntegrationAdmin,
    'FNB-INTEGRATION-ADMIN': AppRoutes.fnbIntegrationAdmin,
    'FNB_ADMIN': AppRoutes.fnbIntegrationAdmin,
    'MESSAGE_QUEUE': AppRoutes.messageQueueAdmin,
    'MESSAGE_QUEUE_ADMIN': AppRoutes.messageQueueAdmin,
    'MESSAGE-QUEUE-ADMIN': AppRoutes.messageQueueAdmin,
    'PARTNER': AppRoutes.partners,
    'PARTNERS': AppRoutes.partners,
    'BUSINESS_PARTNER': AppRoutes.businessPartners,
    'BUSINESS-PARTNER': AppRoutes.businessPartners,
    'BUSINESS_PARTNERS': AppRoutes.businessPartners,
    'BUSINESS-PARTNERS': AppRoutes.businessPartners,
    'CUSTOMER': AppRoutes.customers,
    'CUSTOMERS': AppRoutes.customers,
    'CLIENT': AppRoutes.clients,
    'CLIENTS': AppRoutes.clients,
    'EMPLOYEE': AppRoutes.employees,
    'EMPLOYEES': AppRoutes.employees,
    'SUPPLIER': AppRoutes.suppliers,
    'SUPPLIERS': AppRoutes.suppliers,
    'PRODUCT-MAINTENANCE': AppRoutes.products,
    'INVENTORY': AppRoutes.inventory,
    'INVENTORY_MANAGEMENT': AppRoutes.inventory,
    'INVENTORY-MANAGEMENT': AppRoutes.inventory,
    'STOCK': AppRoutes.inventory,
    'GOODS_RECEIPT': AppRoutes.inventory,
    'GOODS-RECEIPT': AppRoutes.inventory,
    'PUTAWAY': AppRoutes.inventory,
    'STOCK_ON_HAND': AppRoutes.inventory,
    'STOCK-ON-HAND': AppRoutes.inventory,
    'SALES_ORDER': AppRoutes.inventory,
    'SALES-ORDER': AppRoutes.inventory,
    'INTERNAL_COMMUNICATIONS': AppRoutes.internalCommunications,
    'INTERNAL-COMMUNICATIONS': AppRoutes.internalCommunications,
    'COMMUNICATIONS': AppRoutes.internalCommunications,
    'EMPLOYEE_ENGAGEMENT': AppRoutes.internalCommunications,
    'EMPLOYEE-ENGAGEMENT': AppRoutes.internalCommunications,
    'ENGAGEMENT': AppRoutes.internalCommunications,
    'APPOINTMENT': AppRoutes.appointments,
    'APPOINTMENTS': AppRoutes.appointments,
    'APPOINTMENT_BOOKING': AppRoutes.appointments,
    'APPOINTMENT-BOOKING': AppRoutes.appointments,
    'BOOKING': AppRoutes.appointments,
    'BOOKINGS': AppRoutes.appointments,
    'CALENDAR': AppRoutes.calendar,
    
    // Funeral Management
    'FUNERAL': AppRoutes.funeralDashboard,
    'FUNERAL_MANAGEMENT': AppRoutes.funeralDashboard,
    'MORTUARY': AppRoutes.funeralMortuary,
    'MORTUARY_INVENTORY': AppRoutes.funeralMortuary,
    'PICKUP_REQUESTS': AppRoutes.funeralPickups,
    'PICKUP_REQUEST': AppRoutes.funeralPickups,
    'FUNERAL_SERVICE_REQUEST': AppRoutes.funeralServiceRequests,
    'FUNERAL_SERVICE_REQUESTS': AppRoutes.funeralServiceRequests,
    'FUNERAL_SERVICE_REQUEST_SEARCH': AppRoutes.funeralServiceRequests,
    'FUNERAL_ARRANGEMENT': AppRoutes.funeralNewServiceRequest,
    'FUNERAL_ARRANGEMENT_CREATE': AppRoutes.funeralNewServiceRequest,
    'CORPSE_CHECK_IN': AppRoutes.funeralPickups, // Usually happens via Pickups
    'CORPSE_CHECK_OUT': AppRoutes.funeralMortuary, // Usually happens via Mortuary
    'FUNERAL_PACKAGE': AppRoutes.funeralPackageSetup,
    'FUNERAL_PACKAGES': AppRoutes.funeralPackageSetup,
    'FUNERAL_PACKAGE_SETUP': AppRoutes.funeralPackageSetup,
  };

  static String? getRoutePath(String key) {
    final upperKey = key.toUpperCase().replaceAll('-', '_').replaceAll(' ', '_');
    final groupRoute = FeatureGroupRegistry.routeForGroup(key);
    if (groupRoute != null) return groupRoute;

    final route = _mappings[upperKey];
    if (route != null) return route;
    
    return _mappings[key.toUpperCase()];
  }
}
