import 'package:flutter/material.dart';
import '../services/supplier_network_service.dart';

class SupplierNetworkScreen extends StatefulWidget{const SupplierNetworkScreen({super.key});@override State<SupplierNetworkScreen>createState()=>_SupplierNetworkScreenState();}
class _SupplierNetworkScreenState extends State<SupplierNetworkScreen>{final s=SupplierNetworkService();bool loading=true;String? error;List<Map<String,dynamic>>orders=[];@override void initState(){super.initState();load();}Future<void>load()async{setState((){loading=true;error=null;});try{final x=await s.orders();if(mounted)setState((){orders=x;loading=false;});}catch(e){if(mounted)setState((){error='$e';loading=false;});}}
@override Widget build(BuildContext context)=>Scaffold(appBar:AppBar(title:const Text('Incoming Customer Orders'),actions:[IconButton(onPressed:load,icon:const Icon(Icons.refresh))]),body:loading?const Center(child:CircularProgressIndicator()):error!=null?Center(child:Text(error!)):orders.isEmpty?const Center(child:Text('No customer purchase orders have been received.')):ListView.builder(padding:const EdgeInsets.all(16),itemCount:orders.length,itemBuilder:(c,i){final o=orders[i];return Card(child:ListTile(title:Text('${o['order_no']} · ${o['customer_name']??''}'),subtitle:Text('Customer PO ${o['buyer_purchase_order_no']}\n${o['funeral_reference']??''}'),trailing:Chip(label:Text('${o['status']}')),onTap:()=>Navigator.push(c,MaterialPageRoute(builder:(_)=>_OrderPage('${o['id']}'))).then((_)=>load()))); }));}

class _OrderPage extends StatefulWidget{final String id;const _OrderPage(this.id);@override State<_OrderPage>createState()=>_OrderPageState();}
class _OrderPageState extends State<_OrderPage>{final s=SupplierNetworkService();Map<String,dynamic>?o;bool loading=true;@override void initState(){super.initState();load();}Future<void>load()async{final x=await s.order(widget.id);if(mounted)setState((){o=x;loading=false;});}Future<void>act(Future<Map<String,dynamic>> Function()f)async{try{await f();await load();}catch(e){if(mounted)ScaffoldMessenger.of(context).showSnackBar(SnackBar(content:Text('$e')));}}
Future<void>reserve(List<Map<String,dynamic>>lines)async{String line='${lines.first['id']}';final asset=TextEditingController(),employee=TextEditingController(),quantity=TextEditingController(text:'1');final ok=await showDialog<bool>(context:context,builder:(c)=>AlertDialog(title:const Text('Reserve Resource'),content:Column(mainAxisSize:MainAxisSize.min,children:[DropdownButtonFormField<String>(initialValue:line,items:lines.map((l)=>DropdownMenuItem(value:'${l['id']}',child:Text('${l['description']}'))).toList(),onChanged:(v)=>line=v!,decoration:const InputDecoration(labelText:'Order line')),TextField(controller:asset,decoration:const InputDecoration(labelText:'Asset ID (vehicle, machine, tent pool)')),TextField(controller:employee,decoration:const InputDecoration(labelText:'Employee partner ID')),TextField(controller:quantity,keyboardType:TextInputType.number,decoration:const InputDecoration(labelText:'Quantity'))]),actions:[TextButton(onPressed:()=>Navigator.pop(c,false),child:const Text('Cancel')),FilledButton(onPressed:()=>Navigator.pop(c,true),child:const Text('Reserve'))]));if(ok==true)await act(()=>s.reserve(widget.id,{'lineId':line,if(asset.text.trim().isNotEmpty)'assetId':asset.text.trim(),if(employee.text.trim().isNotEmpty)'employeePartnerId':employee.text.trim(),'quantity':num.tryParse(quantity.text)??1}));}
@override Widget build(BuildContext context){if(loading)return const Scaffold(body:Center(child:CircularProgressIndicator()));final lines=List<Map<String,dynamic>>.from(o!['lines'] as List);final status='${o!['status']}';return Scaffold(appBar:AppBar(title:Text('${o!['order_no']}')),body:ListView(padding:const EdgeInsets.all(20),children:[Text('${o!['customer_name']??''}',style:Theme.of(context).textTheme.titleLarge),Text('Customer PO ${o!['buyer_purchase_order_no']} · $status'),if('${o!['funeral_reference']??''}'.isNotEmpty)Text('Funeral ${o!['funeral_reference']}'),const SizedBox(height:16),...lines.map((l)=>Card(child:ListTile(title:Text('${l['description']}'),subtitle:Text('Requested ${l['requested_quantity']} ${l['uom']} · Confirmed ${l['confirmed_quantity']}'),trailing:Text('R ${l['unit_price']}')))),const SizedBox(height:16),Wrap(spacing:8,runSpacing:8,children:[if(status=='RECEIVED'||status=='UNDER_REVIEW')FilledButton(onPressed:()=>act(()=>s.respond(widget.id,'ACCEPTED')),child:const Text('Accept and Schedule')),if(status=='RECEIVED'||status=='UNDER_REVIEW')OutlinedButton(onPressed:()=>act(()=>s.respond(widget.id,'CHANGE_PROPOSED',note:'Supplier proposed a schedule or commercial change')),child:const Text('Propose Change')),if(status=='RECEIVED'||status=='UNDER_REVIEW')OutlinedButton(onPressed:()=>act(()=>s.respond(widget.id,'DECLINED',note:'Capacity unavailable')),child:const Text('Decline')),if(lines.isNotEmpty&&['ACCEPTED','PARTIALLY_ACCEPTED','SCHEDULED','IN_PROGRESS'].contains(status))OutlinedButton.icon(onPressed:()=>reserve(lines),icon:const Icon(Icons.event_available),label:const Text('Reserve Resource')),if(['ACCEPTED','PARTIALLY_ACCEPTED','SCHEDULED','IN_PROGRESS'].contains(status))FilledButton(onPressed:()=>act(()=>s.complete(widget.id)),child:const Text('Confirm Completion')),if(status=='COMPLETED')FilledButton(onPressed:()=>act(()=>s.invoice(widget.id)),child:const Text('Generate Invoice'))]) ]));}}

class SupplierNetworkConnectionsScreen extends StatefulWidget{const SupplierNetworkConnectionsScreen({super.key});@override State<SupplierNetworkConnectionsScreen>createState()=>_ConnectionsState();}
class _ConnectionsState extends State<SupplierNetworkConnectionsScreen>{final s=SupplierNetworkService();List<Map<String,dynamic>>items=[];bool loading=true;@override void initState(){super.initState();load();}Future<void>load()async{final x=await s.connections();if(mounted)setState((){items=x;loading=false;});}
Future<void>add()async{final tenant=TextEditingController(),partner=TextEditingController(),remotePartner=TextEditingController();String type='SUPPLIER';final ok=await showDialog<bool>(context:context,builder:(c)=>StatefulBuilder(builder:(c,setLocal)=>AlertDialog(title:const Text('MAWA Trading Connection'),content:Column(mainAxisSize:MainAxisSize.min,children:[TextField(controller:tenant,decoration:const InputDecoration(labelText:'Remote tenant ID')),TextField(controller:partner,decoration:const InputDecoration(labelText:'Local partner ID')),TextField(controller:remotePartner,decoration:const InputDecoration(labelText:'Partner ID in remote tenant')),DropdownButtonFormField<String>(initialValue:type,items:const[DropdownMenuItem(value:'SUPPLIER',child:Text('Supplier')),DropdownMenuItem(value:'BUYER',child:Text('Buyer'))],onChanged:(v)=>setLocal(()=>type=v!),decoration:const InputDecoration(labelText:'Relationship'))]),actions:[TextButton(onPressed:()=>Navigator.pop(c,false),child:const Text('Cancel')),FilledButton(onPressed:()=>Navigator.pop(c,true),child:const Text('Activate'))])));if(ok==true){await s.saveConnection({'remoteTenantId':tenant.text,'localPartnerId':partner.text,'remotePartnerId':remotePartner.text,'relationshipType':type,'status':'ACTIVE','allowPurchaseOrders':true,'allowInvoices':true});await load();}}
@override Widget build(BuildContext context)=>Scaffold(appBar:AppBar(title:const Text('MAWA Trading Connections'),actions:[IconButton(onPressed:add,icon:const Icon(Icons.add))]),body:loading?const Center(child:CircularProgressIndicator()):ListView.builder(padding:const EdgeInsets.all(16),itemCount:items.length,itemBuilder:(c,i){final x=items[i];return Card(child:ListTile(title:Text('${x['local_partner_name']??x['local_partner_id']}'),subtitle:Text('${x['relationship_type']} · Remote tenant ${x['remote_tenant_id']}'),trailing:Chip(label:Text('${x['status']}'))));}));}
