import 'dart:typed_data';
import 'package:intl/intl.dart';
import 'package:pdf/pdf.dart';
import 'package:pdf/widgets.dart' as pw;
import '../models/case_trust.dart';
import '../../../core/pdf/company_pdf_branding.dart';
import '../../../core/utils/app_date_utils.dart';

class CaseTrustPdfService {
  static final CaseTrustPdfService _instance = CaseTrustPdfService._internal();
  factory CaseTrustPdfService() => _instance;
  CaseTrustPdfService._internal();

  Future<Uint8List> generateTrustReceiptPdf(CaseTrustTransaction transaction) async {
    final doc = pw.Document();

    final branding = await CompanyPdfBranding.load();

    doc.addPage(
      pw.Page(
        pageFormat: PdfPageFormat.a4,
        margin: const pw.EdgeInsets.all(40),
        build: (pw.Context context) => pw.Column(
          crossAxisAlignment: pw.CrossAxisAlignment.start,
          children: [
            branding.header(),
            pw.SizedBox(height: 30),
            pw.Center(
              child: pw.Text('TRUST RECEIPT', style: pw.TextStyle(fontSize: 24, fontWeight: pw.FontWeight.bold, color: PdfColors.blue900)),
            ),
            pw.SizedBox(height: 30),
            _buildReceiptInfo(transaction),
            pw.SizedBox(height: 40),
            pw.Divider(color: PdfColors.grey400),
            pw.SizedBox(height: 10),
            pw.Center(
              child: pw.Text('Received into Trust Account', style: pw.TextStyle(fontWeight: pw.FontWeight.bold, fontSize: 14)),
            ),
            pw.Spacer(),
            pw.Divider(color: PdfColors.grey300),
            pw.Row(
              mainAxisAlignment: pw.MainAxisAlignment.spaceBetween,
              children: [
                pw.Text('Generated by mawa', style: const pw.TextStyle(fontSize: 8, color: PdfColors.grey500)),
                pw.Text(AppDateUtils.displayDateTimePattern(DateTime.now().toUtc(), 'yyyy-MM-dd HH:mm:ss'), style: const pw.TextStyle(fontSize: 8, color: PdfColors.grey500)),
              ],
            ),
          ],
        ),
      ),
    );

    return doc.save();
  }

  pw.Widget _buildReceiptInfo(CaseTrustTransaction tx) {
    final amount = NumberFormat.currency(symbol: 'R ', locale: 'en_ZA').format(tx.amountCents / 100);
    final dateStr = AppDateUtils.displayDateTimePattern(tx.transactionDate, 'yyyy-MM-dd HH:mm', fallback: '-');

    return pw.Container(
      padding: const pw.EdgeInsets.all(20),
      decoration: pw.BoxDecoration(
        border: pw.Border.all(color: PdfColors.grey300),
        borderRadius: const pw.BorderRadius.all(pw.Radius.circular(8)),
      ),
      child: pw.Column(
        children: [
          _receiptRow('Transaction No:', tx.transactionNo),
          _receiptRow('Date/Time:', dateStr),
          pw.Divider(color: PdfColors.grey200),
          _receiptRow('Case ID:', tx.caseId),
          _receiptRow('Client Partner ID:', tx.clientPartnerId),
          pw.Divider(color: PdfColors.grey200),
          _receiptRow('Payment Method:', tx.paymentMethod ?? '-'),
          _receiptRow('Reference Number:', tx.referenceNo ?? '-'),
          _receiptRow('Bank Reference:', tx.bankReference ?? '-'),
          _receiptRow('Description:', tx.description ?? '-'),
          _receiptRow('Received By:', tx.createdBy ?? '-'),
          pw.SizedBox(height: 10),
          pw.Row(
            mainAxisAlignment: pw.MainAxisAlignment.spaceBetween,
            children: [
              pw.Text('AMOUNT:', style: pw.TextStyle(fontSize: 16, fontWeight: pw.FontWeight.bold)),
              pw.Text(amount, style: pw.TextStyle(fontSize: 18, fontWeight: pw.FontWeight.bold, color: PdfColors.blue900)),
            ],
          ),
        ],
      ),
    );
  }

  pw.Widget _receiptRow(String label, String value) {
    return pw.Padding(
      padding: const pw.EdgeInsets.symmetric(vertical: 4),
      child: pw.Row(
        mainAxisAlignment: pw.MainAxisAlignment.spaceBetween,
        children: [
          pw.Text(label, style: pw.TextStyle(fontWeight: pw.FontWeight.bold, fontSize: 10)),
          pw.Text(value, style: const pw.TextStyle(fontSize: 10)),
        ],
      ),
    );
  }

}
