import 'dart:convert';
import 'dart:typed_data';
import 'package:intl/intl.dart';
import 'package:pdf/pdf.dart';
import 'package:pdf/widgets.dart' as pw;
import 'package:printing/printing.dart';
import 'package:shared_preferences/shared_preferences.dart';
import '../models/case_trust.dart';
import '../../../core/services/setting_service.dart';
import '../../../core/api_client.dart';

class CaseTrustPdfService {
  static final CaseTrustPdfService _instance = CaseTrustPdfService._internal();
  factory CaseTrustPdfService() => _instance;
  CaseTrustPdfService._internal();

  Future<Uint8List> generateTrustReceiptPdf(CaseTrustTransaction transaction) async {
    final doc = pw.Document();

    // Load company info
    List<dynamic> settings = [];
    try {
      settings = await SettingService().getSettings();
    } catch (e) {
      print('Error loading settings for PDF: $e');
    }

    final companyName = _getSetting(settings, 'NAME', 'mawa');
    final companyAddress1 = _getSetting(settings, 'ADDRESS-LINE-1', '');
    final companyAddress2 = _getSetting(settings, 'ADDRESS-LINE-2', '');
    final companyCity = _getSetting(settings, 'CITY', '');
    final companyPostalCode = _getSetting(settings, 'POSTAL-CODE', '');
    final companyEmail = _getSetting(settings, 'EMAIL', '');
    final companyPhone = _getSetting(settings, 'PHONE', '');

    // Load Logo if available
    pw.MemoryImage? logoImage;
    try {
      final logoBase64 = await _loadLogoBase64();
      if (logoBase64 != null) {
        logoImage = pw.MemoryImage(base64Decode(logoBase64));
      }
    } catch (e) {
      print('Error loading logo for PDF: $e');
    }

    doc.addPage(
      pw.Page(
        pageFormat: PdfPageFormat.a4,
        margin: const pw.EdgeInsets.all(40),
        build: (pw.Context context) => pw.Column(
          crossAxisAlignment: pw.CrossAxisAlignment.start,
          children: [
            _buildHeader(companyName, companyAddress1, companyAddress2, companyCity, companyPostalCode, companyEmail, companyPhone, logoImage),
            pw.SizedBox(height: 30),
            pw.Center(
              child: pw.Text('TRUST RECEIPT', style: pw.TextStyle(fontSize: 24, fontWeight: pw.FontWeight.bold, color: PdfColors.blue900)),
            ),
            pw.SizedBox(height: 30),
            _buildReceiptInfo(transaction),
            pw.SizedBox(height: 40),
            pw.Divider(color: PdfColors.grey400),
            pw.SizedBox(height: 10),
            pw.Center(
              child: pw.Text('Received into Trust Account', style: pw.TextStyle(fontWeight: pw.FontWeight.bold, fontSize: 14)),
            ),
            pw.Spacer(),
            pw.Divider(color: PdfColors.grey300),
            pw.Row(
              mainAxisAlignment: pw.MainAxisAlignment.spaceBetween,
              children: [
                pw.Text('Generated by mawa', style: const pw.TextStyle(fontSize: 8, color: PdfColors.grey500)),
                pw.Text(DateFormat('yyyy-MM-dd HH:mm:ss').format(DateTime.now()), style: const pw.TextStyle(fontSize: 8, color: PdfColors.grey500)),
              ],
            ),
          ],
        ),
      ),
    );

    return doc.save();
  }

  pw.Widget _buildHeader(String name, String a1, String a2, String city, String pc, String email, String phone, pw.MemoryImage? logo) {
    return pw.Row(
      mainAxisAlignment: pw.MainAxisAlignment.spaceBetween,
      crossAxisAlignment: pw.CrossAxisAlignment.start,
      children: [
        pw.Column(
          crossAxisAlignment: pw.CrossAxisAlignment.start,
          children: [
            if (logo != null)
              pw.Container(height: 60, width: 60, child: pw.Image(logo))
            else
              pw.Text(name, style: pw.TextStyle(fontSize: 18, fontWeight: pw.FontWeight.bold, color: PdfColors.blue900)),
            pw.SizedBox(height: 4),
            pw.Text(a1, style: const pw.TextStyle(fontSize: 9)),
            if (a2.isNotEmpty) pw.Text(a2, style: const pw.TextStyle(fontSize: 9)),
            pw.Text('$city, $pc', style: const pw.TextStyle(fontSize: 9)),
            pw.Text('Phone: $phone', style: const pw.TextStyle(fontSize: 9)),
            pw.Text('Email: $email', style: const pw.TextStyle(fontSize: 9)),
          ],
        ),
      ],
    );
  }

  pw.Widget _buildReceiptInfo(CaseTrustTransaction tx) {
    final amount = NumberFormat.currency(symbol: 'R ', locale: 'en_ZA').format(tx.amountCents / 100);
    final dateStr = tx.transactionDate != null ? DateFormat('yyyy-MM-dd HH:mm').format(tx.transactionDate!) : '-';

    return pw.Container(
      padding: const pw.EdgeInsets.all(20),
      decoration: pw.BoxDecoration(
        border: pw.Border.all(color: PdfColors.grey300),
        borderRadius: const pw.BorderRadius.all(pw.Radius.circular(8)),
      ),
      child: pw.Column(
        children: [
          _receiptRow('Transaction No:', tx.transactionNo),
          _receiptRow('Date/Time:', dateStr),
          pw.Divider(color: PdfColors.grey200),
          _receiptRow('Case ID:', tx.caseId),
          _receiptRow('Client Partner ID:', tx.clientPartnerId),
          pw.Divider(color: PdfColors.grey200),
          _receiptRow('Payment Method:', tx.paymentMethod ?? '-'),
          _receiptRow('Reference Number:', tx.referenceNo ?? '-'),
          _receiptRow('Bank Reference:', tx.bankReference ?? '-'),
          _receiptRow('Description:', tx.description ?? '-'),
          _receiptRow('Received By:', tx.createdBy ?? '-'),
          pw.SizedBox(height: 10),
          pw.Row(
            mainAxisAlignment: pw.MainAxisAlignment.spaceBetween,
            children: [
              pw.Text('AMOUNT:', style: pw.TextStyle(fontSize: 16, fontWeight: pw.FontWeight.bold)),
              pw.Text(amount, style: pw.TextStyle(fontSize: 18, fontWeight: pw.FontWeight.bold, color: PdfColors.blue900)),
            ],
          ),
        ],
      ),
    );
  }

  pw.Widget _receiptRow(String label, String value) {
    return pw.Padding(
      padding: const pw.EdgeInsets.symmetric(vertical: 4),
      child: pw.Row(
        mainAxisAlignment: pw.MainAxisAlignment.spaceBetween,
        children: [
          pw.Text(label, style: pw.TextStyle(fontWeight: pw.FontWeight.bold, fontSize: 10)),
          pw.Text(value, style: const pw.TextStyle(fontSize: 10)),
        ],
      ),
    );
  }

  String _getSetting(List<dynamic> settings, String attribute, String defaultValue) {
    try {
      return settings.firstWhere((s) => s.type == 'TENANT' && s.attribute == attribute).value;
    } catch (_) {
      return defaultValue;
    }
  }

  Future<String?> _loadLogoBase64() async {
    try {
      final prefs = await SharedPreferences.getInstance();
      final tenantId = prefs.getString('tenant');
      if (tenantId == null) return null;

      final response = await ApiClient().get('/v2/attachment?objectId=$tenantId');
      if (response.statusCode == 200) {
        final List<dynamic> data = jsonDecode(response.body);
        final logoAttachment = data.firstWhere(
          (a) => a['documentType']?['id'] == 'LOGO',
          orElse: () => null,
        );

        if (logoAttachment != null) {
          final res = await ApiClient().get(
            '/v2/attachment/${logoAttachment['id']}',
            accept: 'text/plain',
          );
          if (res.statusCode == 200) {
            return res.body.replaceAll('"', '');
          }
        }
      }
    } catch (e) {
      print('Error fetching logo: $e');
    }
    return null;
  }
}
