import 'package:flutter/material.dart';
import '../../services/funeral_resource_planning_service.dart';
import '../../../partners/partner_service.dart';
import '../../data/funeral_api.dart';

class FuneralResourcePlanningPage extends StatefulWidget {
  final bool configurationOnly;
  const FuneralResourcePlanningPage({super.key,this.configurationOnly=false});
  @override State<FuneralResourcePlanningPage> createState()=>_State();
}
class _State extends State<FuneralResourcePlanningPage>{
  final _service=FuneralResourcePlanningService(); Map<String,dynamic>? _config; List<Map<String,dynamic>> _plans=[]; bool _loading=true;
  @override void initState(){super.initState();_load();}
  Future<void> _load()async{setState(()=>_loading=true);try{final c=await _service.configuration();final p=widget.configurationOnly||c['status']=='DISABLED'?<Map<String,dynamic>>[]:await _service.plans();if(mounted)setState((){_config=c;_plans=p;});}catch(e){if(mounted)ScaffoldMessenger.of(context).showSnackBar(SnackBar(content:Text('$e')));}finally{if(mounted)setState(()=>_loading=false);}}
  Future<void> _toggle(bool enabled)async{final c=_config!;final result=await _service.saveConfiguration({'enabled':enabled,'autoCreatePlans':c['autoCreatePlans'],'requireReadiness':c['requireReadiness'],'provisionalExpiryHours':c['provisionalExpiryHours'],'allowThirdPartyLeasing':c['allowThirdPartyLeasing'],'requireApprovedPo':c['requireApprovedPo']});setState(()=>_config=result);await _load();}
  @override Widget build(BuildContext context){return Scaffold(appBar:AppBar(title:Text(widget.configurationOnly?'Funeral Resource Planning Configuration':'Funeral Resource Planning')),body:_loading?const Center(child:CircularProgressIndicator()):_config==null?const Center(child:Text('Configuration unavailable')):ListView(padding:const EdgeInsets.all(24),children:[Card(child:SwitchListTile(title:const Text('Enable Funeral Resource Planning'),subtitle:Text('Tenant status: ${_config!['status']}'),value:_config!['status']=='ENABLED',onChanged:_toggle)),if(widget.configurationOnly)..._settings(),if(!widget.configurationOnly&&_config!['status']=='DISABLED')const Card(child:Padding(padding:EdgeInsets.all(24),child:Text('Resource planning is not enabled for this tenant.'))),if(!widget.configurationOnly&&_config!['status']!='DISABLED')..._plans.map((p)=>Card(child:ListTile(title:Text('${p['service_request_no']??''} · ${p['deceased_name']??''}'),subtitle:Text('${p['funeral_date']??''} · ${p['funeral_area']??''}\n${p['unresolved_count']??0} mandatory requirements unresolved'),trailing:Chip(label:Text('${p['status']}')),onTap:()=>Navigator.of(context).push(MaterialPageRoute(builder:(_)=>_PlanPage(id:'${p['id']}'))).then((_)=>_load()))))]));}
  List<Widget> _settings()=>[
    CheckboxListTile(title:const Text('Automatically create plans'),value:_config!['autoCreatePlans']==true,onChanged:(v)=>_saveOption('autoCreatePlans',v)),
    CheckboxListTile(title:const Text('Require resource readiness'),value:_config!['requireReadiness']==true,onChanged:(v)=>_saveOption('requireReadiness',v)),
    CheckboxListTile(title:const Text('Allow third-party leasing'),value:_config!['allowThirdPartyLeasing']==true,onChanged:(v)=>_saveOption('allowThirdPartyLeasing',v)),
    CheckboxListTile(title:const Text('Require approved PO before readiness'),value:_config!['requireApprovedPo']==true,onChanged:(v)=>_saveOption('requireApprovedPo',v)),
  ];
  Future<void> _saveOption(String key,bool? value)async{final body=Map<String,dynamic>.from(_config!);body[key]=value;body['enabled']=body['status']=='ENABLED';setState(()=>_loading=true);try{_config=await _service.saveConfiguration(body);}finally{if(mounted)setState(()=>_loading=false);}}
}

class _PlanPage extends StatefulWidget{final String id;const _PlanPage({required this.id});@override State<_PlanPage> createState()=>_PlanState();}
class _PlanState extends State<_PlanPage>{final s=FuneralResourcePlanningService();Map<String,dynamic>? plan;bool loading=true;@override void initState(){super.initState();load();}Future<void>load()async{setState(()=>loading=true);try{plan=await s.plan(widget.id);}finally{if(mounted)setState(()=>loading=false);}}
@override Widget build(BuildContext context)=>Scaffold(appBar:AppBar(title:Text(plan?['service_request_no']??'Resource Plan')),floatingActionButton:plan!=null?FloatingActionButton.extended(onPressed:_ready,label:const Text('Confirm Ready'),icon:const Icon(Icons.task_alt)):null,body:loading?const Center(child:CircularProgressIndicator()):ListView(padding:const EdgeInsets.all(20),children:[Text('${plan!['deceased_name']} · ${plan!['funeral_date']}',style:Theme.of(context).textTheme.titleLarge),const SizedBox(height:12),...(plan!['items'] as List).map((raw){final i=Map<String,dynamic>.from(raw as Map);return Card(child:ListTile(title:Text('${i['name']} (${i['required_quantity']} ${i['uom']})'),subtitle:Text('${i['resource_type']} · ${i['start_at']} – ${i['end_at']}\nAllocated: ${i['allocated_quantity']} · ${i['status']}'),trailing:PopupMenuButton<String>(onSelected:(v)=>v=='internal'?_internal(i):_external(i),itemBuilder:(_)=>[const PopupMenuItem(value:'internal',child:Text('Use own resource')),if(_canExternal(i))const PopupMenuItem(value:'external',child:Text('Lease from third party'))])));} )]));
bool _canExternal(Map<String,dynamic>i)=>i['sourcing_mode']!='INTERNAL_ONLY';
Future<void>_internal(Map<String,dynamic>i)async{if(i['resource_type']=='EMPLOYEE'){final people=await FuneralApi().getEmployees();if(!mounted)return;final selected=await showDialog<String>(context:context,builder:(c)=>SimpleDialog(title:const Text('Select employee'),children:people.map((p)=>SimpleDialogOption(onPressed:()=>Navigator.pop(c,p.id),child:Text(p.fullName))).toList()));if(selected!=null){await s.allocateEmployee('${i['id']}',selected,1);await load();}}else{final assets=await s.assets('${i['id']}');if(!mounted)return;final selected=await showDialog<String>(context:context,builder:(c)=>SimpleDialog(title:const Text('Select available resource'),children:assets.map((a)=>SimpleDialogOption(onPressed:()=>Navigator.pop(c,'${a['id']}'),child:Text('${a['asset_no']} · ${a['name']}'))).toList()));if(selected!=null){await s.allocateAsset('${i['id']}',selected,1);await load();}}}
Future<void>_external(Map<String,dynamic>i)async{final suppliers=await PartnerService().getPartnersByRole('SUPPLIER');if(!mounted)return;final supplier=await showDialog<String>(context:context,builder:(c)=>SimpleDialog(title:const Text('Select approved supplier'),children:suppliers.map((p)=>SimpleDialogOption(onPressed:()=>Navigator.pop(c,p.id),child:Text(p.fullName))).toList()));if(supplier==null)return;final product=TextEditingController(text:'${i['product_id']??''}');final cost=TextEditingController();if(!mounted)return;final ok=await showDialog<bool>(context:context,builder:(c)=>AlertDialog(title:const Text('Third-party lease'),content:Column(mainAxisSize:MainAxisSize.min,children:[TextField(controller:product,decoration:const InputDecoration(labelText:'Procurement product ID')),TextField(controller:cost,decoration:const InputDecoration(labelText:'Unit cost'),keyboardType:TextInputType.number)]),actions:[TextButton(onPressed:()=>Navigator.pop(c,false),child:const Text('Cancel')),FilledButton(onPressed:()=>Navigator.pop(c,true),child:const Text('Create draft PO'))]));if(ok==true){await s.lease('${i['id']}',supplier,product.text,num.tryParse('${i['required_quantity']}')??1,num.tryParse(cost.text)??0);await load();}}
Future<void>_ready()async{try{plan=await s.confirmReady(widget.id);if(mounted)setState((){});}catch(e){if(mounted)ScaffoldMessenger.of(context).showSnackBar(SnackBar(content:Text('$e')));}}
}
