import 'package:flutter/material.dart';
import '../../data/funeral_api.dart';
import '../../data/models/funeral_tenant_option_dto.dart';
import '../../data/models/tenant_trust_relationship_dto.dart';

class TrustedTenantsPage extends StatefulWidget { const TrustedTenantsPage({super.key}); @override State<TrustedTenantsPage> createState()=>_State(); }
class _State extends State<TrustedTenantsPage> {
 final api=FuneralApi(); bool loading=true; String? error; List<TenantTrustRelationshipDto> rows=[]; List<FuneralTenantOptionDto> tenants=[];
 @override void initState(){super.initState();load();}
 Future<void> load() async { setState(()=>loading=true); try { final r=await Future.wait([api.getTrustedTenants(),api.getAvailableTenantOptions()]); if(mounted)setState((){rows=r[0] as List<TenantTrustRelationshipDto>;tenants=r[1] as List<FuneralTenantOptionDto>;error=null;}); } catch(e){if(mounted)setState(()=>error=e.toString());} finally{if(mounted)setState(()=>loading=false);} }
 Future<void> request() async { String? selected; bool lookup=true,create=true,status=true; final ok=await showDialog<bool>(context:context,builder:(c)=>StatefulBuilder(builder:(c,set)=>AlertDialog(title:const Text('Request trusted tenant'),content:SizedBox(width:480,child:Column(mainAxisSize:MainAxisSize.min,children:[DropdownButtonFormField<String>(decoration:const InputDecoration(labelText:'Membership and claims tenant',border:OutlineInputBorder()),items:tenants.map((t)=>DropdownMenuItem(value:t.id,child:Text(t.name))).toList(),onChanged:(v)=>set(()=>selected=v)),CheckboxListTile(value:lookup,onChanged:(v)=>set(()=>lookup=v??true),title:const Text('Allow membership lookup')),CheckboxListTile(value:create,onChanged:(v)=>set(()=>create=v??true),title:const Text('Allow claim creation')),CheckboxListTile(value:status,onChanged:(v)=>set(()=>status=v??true),title:const Text('Allow claim status read'))])),actions:[TextButton(onPressed:()=>Navigator.pop(c,false),child:const Text('CANCEL')),FilledButton(onPressed:selected==null?null:()=>Navigator.pop(c,true),child:const Text('REQUEST'))]))); if(ok==true&&selected!=null){await api.requestTrustedTenant(TenantTrustRelationshipDto(providerTenantId:selected,membershipLookupAllowed:lookup,claimCreationAllowed:create,claimStatusReadAllowed:status));await load();}}
 Future<void> action(TenantTrustRelationshipDto r,String s) async {await api.updateTrustedTenantStatus(r.id!,s);await load();}
 @override Widget build(BuildContext context)=>Scaffold(appBar:AppBar(title:const Text('Trusted Tenants'),actions:[IconButton(onPressed:load,icon:const Icon(Icons.refresh))]),floatingActionButton:FloatingActionButton.extended(onPressed:request,icon:const Icon(Icons.add_link),label:const Text('Request trust')),body:loading?const Center(child:CircularProgressIndicator()):error!=null?Center(child:Text(error!)):ListView.builder(padding:const EdgeInsets.all(16),itemCount:rows.length,itemBuilder:(c,i){final r=rows[i];final incoming=r.providerTenantId!=null&&r.providerTenantName!=null;return Card(child:ListTile(leading:Icon(r.status=='APPROVED'?Icons.verified_user:Icons.pending_actions),title:Text('${r.requesterTenantName ?? r.requesterTenantId} → ${r.providerTenantName ?? r.providerTenantId}'),subtitle:Text('Status: ${r.status} • Membership lookup: ${r.membershipLookupAllowed?'Yes':'No'} • Claim creation: ${r.claimCreationAllowed?'Yes':'No'} • Status read: ${r.claimStatusReadAllowed?'Yes':'No'}'),trailing:Wrap(children:[if(r.status=='PENDING') IconButton(tooltip:'Approve',onPressed:()=>action(r,'APPROVED'),icon:const Icon(Icons.check_circle)),if(r.status=='PENDING') IconButton(tooltip:'Reject',onPressed:()=>action(r,'REJECTED'),icon:const Icon(Icons.cancel)),if(r.status=='APPROVED') IconButton(tooltip:'Suspend',onPressed:()=>action(r,'SUSPENDED'),icon:const Icon(Icons.pause_circle)),if(r.status!='REVOKED') IconButton(tooltip:'Revoke',onPressed:()=>action(r,'REVOKED'),icon:const Icon(Icons.link_off))]));}));
}
