import 'package:flutter/material.dart';
import 'package:shared_preferences/shared_preferences.dart';
import '../services/card_terminal_service.dart';
import '../../../core/errors/app_error.dart';

class CardTerminalConfigurationScreen extends StatefulWidget{const CardTerminalConfigurationScreen({super.key});@override State<CardTerminalConfigurationScreen> createState()=>_State();}
class _State extends State<CardTerminalConfigurationScreen>{
 final service=CardTerminalService(); List<CardTerminal> rows=[]; bool loading=true;
 @override void initState(){super.initState();load();}
 Future<void> load()async{setState(()=>loading=true);try{rows=await service.list();}catch(e){if(mounted)ScaffoldMessenger.of(context).showSnackBar(SnackBar(content:Text(friendlyErrorMessage(e))));}finally{if(mounted)setState(()=>loading=false);}}
 Future<void> edit([CardTerminal? existing])async{
  final code=TextEditingController(text:existing?.code),name=TextEditingController(text:existing?.name),merchant=TextEditingController(text:existing?.merchantNumber),location=TextEditingController(text:existing?.locationCode);var active=existing?.active??true;
  final result=await showDialog<CardTerminal>(context:context,builder:(ctx)=>StatefulBuilder(builder:(ctx,setLocal)=>AlertDialog(title:Text(existing==null?'Add card terminal':'Edit card terminal'),content:SizedBox(width:520,child:Column(mainAxisSize:MainAxisSize.min,children:[TextField(controller:code,decoration:const InputDecoration(labelText:'Terminal code *',border:OutlineInputBorder())),const SizedBox(height:12),TextField(controller:name,decoration:const InputDecoration(labelText:'Terminal name *',border:OutlineInputBorder())),const SizedBox(height:12),TextField(controller:merchant,decoration:const InputDecoration(labelText:'Merchant number',border:OutlineInputBorder())),const SizedBox(height:12),TextField(controller:location,decoration:const InputDecoration(labelText:'Location code',border:OutlineInputBorder())),SwitchListTile(contentPadding:EdgeInsets.zero,title:const Text('Active'),value:active,onChanged:(v)=>setLocal(()=>active=v))])),actions:[TextButton(onPressed:()=>Navigator.pop(ctx),child:const Text('Cancel')),FilledButton(onPressed:()=>Navigator.pop(ctx,CardTerminal(id:existing?.id??'',code:code.text.trim(),name:name.text.trim(),merchantNumber:merchant.text.trim(),locationCode:location.text.trim(),active:active)),child:const Text('Save'))])));
  code.dispose();name.dispose();merchant.dispose();location.dispose();if(result==null)return;if(result.code.isEmpty||result.name.isEmpty){if(mounted)ScaffoldMessenger.of(context).showSnackBar(const SnackBar(content:Text('Terminal code and name are required.')));return;}try{final p=await SharedPreferences.getInstance();await service.save(result,changedBy:p.getString('userId'));await load();}catch(e){if(mounted)ScaffoldMessenger.of(context).showSnackBar(SnackBar(content:Text(friendlyErrorMessage(e))));}
 }
 @override Widget build(BuildContext context)=>Scaffold(appBar:AppBar(title:const Text('Card Terminals'),actions:[IconButton(onPressed:load,icon:const Icon(Icons.refresh))]),floatingActionButton:FloatingActionButton.extended(onPressed:()=>edit(),icon:const Icon(Icons.add),label:const Text('Add terminal')),body:loading?const Center(child:CircularProgressIndicator()):rows.isEmpty?const Center(child:Text('No card terminals configured.')):ListView.separated(padding:const EdgeInsets.all(24),itemCount:rows.length,separatorBuilder:(_,__)=>const SizedBox(height:10),itemBuilder:(_,i){final t=rows[i];return Card(child:ListTile(leading:CircleAvatar(child:const Icon(Icons.point_of_sale_outlined)),title:Text(t.name),subtitle:Text('${t.code}${(t.merchantNumber??'').isEmpty?'':' • Merchant ${t.merchantNumber}'}${(t.locationCode??'').isEmpty?'':' • ${t.locationCode}'}'),trailing:Wrap(crossAxisAlignment:WrapCrossAlignment.center,children:[Chip(label:Text(t.active?'Active':'Inactive')),IconButton(onPressed:()=>edit(t),icon:const Icon(Icons.edit_outlined))]))); }));
}
